library_task
AnnQK/external-courses pull request #10
Opened 2022-04-15 12:45 UTC by AnnQK

Привет, я переименовала шрифт, просто убрала пробелы. чтобы было проще к нему писать путь. 
Не нашла иконки и изображения, добавила похожие.

2022-04-15 14:11 UTC, spiderpoul requested changes
Всё хорошо, но нужно чтобы макет растягивался по высоте и ширине
![image](https://user-images.githubusercontent.com/23116531/163580952-ccb36566-716b-48a2-ad92-cc5c544c91c8.png)

2022-04-15 14:30 UTC, AnnQK commented
У меня отображается по высоте нормально почему-то. А по ширине нужно, чтобы элементы (кнопки, отображение аккаунта и тд) были прям на краю экрана? или можно сделать, чтобы элементы были в контейнере не до края, а по всей ширине просто фон?

2022-04-15 14:38 UTC, spiderpoul commented
> У меня отображается по высоте нормально почему-то. А по ширине нужно, чтобы элементы (кнопки, отображение аккаунта и тд) были прям на краю экрана? или можно сделать, чтобы элементы были в контейнере не до края, а по всей ширине просто фон?

Это я на большом мониторе смотрел, попробуй уменьшить масштаб и тоже так будет) нужно, чтобы футер/хедер растягивался по ширине при измении разрешения, как минимум для начала поставить `width: 100%`. А футер должен прилипать к низу, то есть основной контент должен растягиваться по все высоте. Можно layout сделать с помощью флексов. Вот тут примеры https://medium.com/@merveyuksek/webpage-layout-examples-with-flexbox-88287f010a08

2022-04-16 11:58 UTC, AnnQK commented
Теперь должно работать, я думаю

2022-04-18 12:09 UTC, spiderpoul commented on src/library_task/style.css
> +    margin-top: auto;
`margin-top: auto` -  пока нет контента - это работает, но не самый лучший вариант..
поставь для `main` - `flex-grow: 1` и когда у тебя появится контент ничего не сломается

2022-04-18 12:09 UTC, spiderpoul commented on src/library_task/style.css
> +    margin-top: auto;
и не забудь, пожалуйста, в приложении нажать на кнопку Revision done, когда поправишь)

2022-04-18 14:50 UTC, AnnQK commented on src/library_task/style.css
> +    margin-top: auto;
Хорошо, сейчас переделаю. Я обычно просто body передавала justify-content: space-between, буду знать.
Приложение что-то вообще из головы вылетело.

2022-04-18 15:05 UTC, spiderpoul commented on src/library_task/style.css
> +main {
желательно переделать на класс, как с хедером и футером, для однообразности

2022-04-18 15:05 UTC, spiderpoul approved these changes

2022-04-18 16:33 UTC, merged